Update database by adding mediaContributors support
thegazelle-ad/wp-to-ghost-transfer pull request #2
Opened 2017-11-12 10:39 UTC by jaisal1024

Added the table mediaContributors_post with author_id's and post_id's to support a many-to-many relationship between authors (who are media contributors) and posts (articles). This will be added to the knex database in the script.

2017-11-12 19:15 UTC, emilgoldsmith requested changes
If you just change the name I think everything looks good :). This is exactly the same as authors_posts right? (that's meant as a good thing)

2017-11-12 19:15 UTC, emilgoldsmith commented on updateDatabaseMediaContributors
> +.dropTableIfExists('mediaContributors_posts')
Maybe just for consistent naming conventions make it `media_contributors_posts` ?

2017-11-19 10:03 UTC, jaisal1024 commented
I just made the requested changes. And yes it is basically the exact same as the other script. But obviously, you should double check before we finalize the code.

2017-11-19 13:45 UTC, emilgoldsmith approved these changes
Yep looks good now :)

2017-11-19 13:45 UTC, merged